### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by AnthonyBronca** [AMBALERT1/Sun-Airbnb#1]
# API Docs:
Please make sure to follow RESTFUL naming convention. We can reference what the table might be for some. For example: `/current-users` can be updated to just be `/users`. Additionally, we should be using camelCasing convention since we are planning to build the backend using Javascript.

## Tasks:

- [x] #3
- [x] #2
- [x] Remove snake_casing from routes and replace them with camelCasing

Note: We do not need to have quotes around the routes in the API docs

# DB Diagram:
Please make sure to make the adjustments to DB Diagram. It is looking better, but we can make some efficiency related changes, as well as follow camelCasing conventions to clean it up:

## Tasks:
- [x] Readjust Spots Table as there are missing attributes (lat, lng).
- [x] Remove aggregate data from the table/s
- [x] Reconsider how the preview Image is being handled for Spots, as we have a SpotImage related table we can use instead to handle preview image/s functionality
- [x] Adjust table attributes to follow camelCase convention and not snake_case convention
- [x] Adjust the image in the API docs to be the updated DB Diagram when complete

# Deadline

Please aim to complete all of these tasks by EOD on Monday, May 13th. We want to aim to finalize these docs so that we can proceed to the next phase of the project life cycle.

**Comment by AMBALERT1** [comment]
Good Evening! I have completed the needed tasks!

**Comment by irelius** [comment]
# API Docs and DB Diagram Review 2

## DB Diagram
- [x] Refer to the API docs and see if "ownerId" is under the Bookings table
- [x] Spots is missing a few columns, refer to the API docs for what those columns are
- [x] "ownerid" under the Spots table does not match what is listed in the API docs
- [x] SpotImage table is missing a column. The API docs won't tell you this outright, but it has to do with Airbnb's feature where it displays a set number of images as the preview images for a particular spot. Think of how one to many relationships work between Spot and SpotImages and how you would determine which images that belong to a particular spot would be decided as a preview image
- [x] "firstname" and "lastname" under the Users table does not match the expected response listed in the API docs
- [x] "reviews" under the Reviews table does not match what is listed in the API docs

## API Docs
- [x] API endpoint for "Get all Spots owned by the Current User" is not ideal. The route does not say anything about which user's spots you are going to be fetching. Also, "user" should be plural
- [x] "Delete a Spot" is missing the syntax to indicate a parameter
- [x] Route for "Get All Reviews of the Current User" is missing something to indicate which user's reviews you are fetching. Also, "review" should be plural
- [x] "Create a Review for a Spot based on the Spot's id" is missing the syntax to indicate a parameter
- [x] "Edit a Review" is missing the syntax to indicate a parameter
- [x] "Delete a Review" is missing the syntax to indicate a parameter
- [x] "Create a Booking from a Spot based on the Spot's id" is missing the syntax to indicate a parameter
- [x] Route for "Delete a Spot Image" is not ideal. Currently, the route implies you'll be deleting a booking, not an image associated with a spot

**Comment by AMBALERT1** [comment]
Working on Review 2 currently under the DB Diagram - "ownerid" under the Spots table does not match what is listed in the API docs

When I look at the API docs and navigate to spots . Its showing "ownerId" and that is correct in my DB. 

Please advise !

**Comment by AMBALERT1** [comment]
Working on Review 2 currently under the DB Diagram - "firstname" and "lastname" under the Users table does not match the expected response listed in the API docs 

When I look at the API docs and navigate to ## USER AUTHENTICATION/AUTHORIZATION (users) its showing "firstName" "lastName" as the output response and that is correct in my DB. 

Please advise

**Comment by irelius** [comment]
# API Docs and DB Diagram Review 3

## DB Diagram
- [x] The "avgstarRating" column under the Spots table is unnecessary. You'll be using a lazy loading method to calculate the average rating of a spot. You can switch to eager loading using aggregation methods at a later point

## API Docs
- [x] "Create a Review for a Spot based on the Spot's id" route is missing the syntax to indicate a parameter
- [x] "Create a Booking from a Spot based on the Spot's id" route should include something within the route to imply you'll be getting a spot. Currently, the route is "/bookings/:spotId". And if I wanted to get a booking for spot number 1, the route would look like "/bookings/1", which reads more like you'll be interacting with booking number 1, not the booking for spot 1

**Comment by AMBALERT1** [comment]
Review 3 has been completed

**Comment by AnthonyBronca** [comment]
# DB Diagram 
- [x] Still missing items. Review the unchecked boxes from the previous reviews for items you are missing.

# API Docs
Approved!
